package net.vys.collection.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "An Author data transfer object")
public class AuthorDTO {
    //@Schema(description = "Author ID autogenerated", example = "1")
    //Long id;
    @Schema(description = "Author name", example = "Tyrion IV")
    @NotBlank(message = "Author name cannot be empty")
    @Size(max = 100, message = "Author name too long")
    private String name;

    public AuthorDTO() {
    }
    
    public AuthorDTO(String name) {
        //this.id = id;
        this.name = name;
    }

    /*public AuthorDTO(Long id, String name) {
        //this.id = id;
        this.name = name;
    }

    /*public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }*/

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
