package net.vys.collection.dto;
import java.util.List;

import io.swagger.v3.oas.annotations.media.Schema;
import net.vys.collection.dto.AuthorResponseDTO;
import net.vys.collection.dto.PublisherResponseDTO;
import net.vys.collection.dto.SerieResponseDTO;
import jakarta.validation.constraints.NotBlank;

public class ComicDTO {
    @Schema(description = "Comic ID autogenerated", example = "1")
    Long id;
    @Schema(description = "Comic title", example = "The Dark Knight Returns")
    @NotBlank(message = "Comic name cannot be empty")
    private String title;
    @Schema(description = "List of Author IDs", example = "[1, 2, 3]")
    private List<Long> authors;// List ID of Authors
    @Schema(description = "Publisher ID", example = "1")
    private Long publisher; // ID of the associated Publisher
    @Schema(description = "Publication year", example = "2020")
    private Integer publicationYear;
    @Schema(description = "Notes about the comic", example = "First appearance of the character")
    private String notes;
    @Schema(description = "Issue number", example = "1")
    private Integer issue;
    @Schema(description = "Serie ID", example = "1")
    private Long serie; // ID of the associated Serie

    public ComicDTO() {}

    public ComicDTO(Long id, String title, List<Long> authors, Long publisher, Integer publicationYear,
                    String notes, Integer issue, Long serie) {
        this.id = id;
        this.title = title;
        this.authors = authors;
        this.publisher = publisher;
        this.publicationYear = publicationYear;
        this.notes = notes;
        this.issue = issue;
        this.serie = serie;
    }

    public Long getId() {return id;}
    public void setId(Long id) {this.id = id;}
    public String getTitle() {return title;}
    public void setTitle(String title) {this.title = title;}
    public List<Long> getAuthors() {return authors;}
    public void setAuthors(List<Long> authors) {this.authors = authors;}
    public Long getPublisher() {return publisher;}
    public void setPublisher(Long publisher) {this.publisher = publisher;}
    public Integer getPublicationYear() {return publicationYear;}
    public void setPublicationYear(Integer publicationYear) {this.publicationYear = publicationYear;}
    public String getNotes() {return notes;}
    public void setNotes(String notes) {this.notes = notes;}
    public Integer getIssue() {return issue;}
    public void setIssue(Integer issue) {this.issue = issue;}
    public Long getSerie() {return serie;}
    public void setSerie(Long serie) {this.serie = serie;}
}
