package net.vys.collection.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;

@Schema(description = "An Serie data transfer object")
public class SerieDTO {
    //@Schema(description = "Serie ID autogenerated", example = "1")
    //Long id;
    @NotBlank(message = "Serie name cannot be empty")
    @Schema(description = "Serie name", example = "Batman")
    private String name;
    @Schema(description = "Number of issues", example = "10")
    private Integer issues;

    public SerieDTO() {}

    public SerieDTO(String name, Integer issues) {
        this.name = name;
        this.issues = issues;
    }

    /*public SerieDTO(Long id, String name, Integer issues) {
        this.id = id;
        this.name = name;
        this.issues = issues;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }*/

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getIssues() {
        return issues;
    }

    public void setIssues(Integer issues) {
        this.issues = issues;
    }
}
